name: Auto-Deploy Laravel Rahantara to cPanel with Symlinks

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v4
      
    # -----------------------------
    # PHP & Composer
    # -----------------------------
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, pdo
    
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
        
    - name: Install Composer dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      
    # -----------------------------
    # Node & Vite
    # -----------------------------
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build assets with Vite
      run: npm run build
      
    # -----------------------------
    # Deployment packaging
    # -----------------------------
    - name: Prepare deployment structure
      run: |
        mkdir -p deployment/rahantara
        mkdir -p deployment/public_html

        # Copy Laravel app excluding public
        rsync -av ./ deployment/rahantara/ \
          --exclude=public \
          --exclude=.git \
          --exclude=node_modules \
          --exclude=tests \
          --exclude=.github \
          --exclude=deployment
          
        # Copy public folder contents
        cp -r public/* deployment/public_html/
        
        # Ensure Vite build is copied
        if [ -d "public/build" ]; then
          cp -r public/build deployment/public_html/
          echo "✓ Build folder copied successfully"
        else
          echo "✗ Build folder missing"
          exit 1
        fi

        # Custom index.php for root domain
        cat > deployment/public_html/index.php << 'EOF'
        <?php
        use Illuminate\Contracts\Http\Kernel;
        use Illuminate\Http\Request;

        define('LARAVEL_START', microtime(true));

        require __DIR__.'/../rahantara/vendor/autoload.php';
        $app = require_once __DIR__.'/../rahantara/bootstrap/app.php';
        $kernel = $app->make(Kernel::class);

        $response = $kernel->handle(
            $request = Request::capture()
        )->send();

        $kernel->terminate($request, $response);
        EOF

        # Public .htaccess
        cat > deployment/public_html/.htaccess << 'EOF'
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews -Indexes
            </IfModule>

            RewriteEngine On

            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_URI} (.+)/$
            RewriteRule ^ %1 [L,R=301]

            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.php [L]
        </IfModule>
        EOF

    # -----------------------------
    # FTP Deploy
    # -----------------------------
    - name: Deploy Laravel App to /rahantara
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PUBLIC_FTP_SERVER }}
        username: ${{ secrets.PUBLIC_FTP_USERNAME }}
        password: ${{ secrets.PUBLIC_FTP_PASSWORD }}
        port: ${{ secrets.PUBLIC_FTP_PORT }}
        local-dir: ./deployment/rahantara/
        server-dir: /rahantara/
        
    - name: Deploy Public Assets to /public_html
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PUBLIC_FTP_SERVER }}
        username: ${{ secrets.PUBLIC_FTP_USERNAME }}
        password: ${{ secrets.PUBLIC_FTP_PASSWORD }}
        port: ${{ secrets.PUBLIC_FTP_PORT }}
        local-dir: ./deployment/public_html/
        server-dir: /public_html/
        
    # -----------------------------
    # Post-deploy (Symlinks + Cache Clear + Restart)
    # -----------------------------
    - name: Post-deployment setup via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          # Storage symlink in public_html
          cd /home/rahe9358/public_html
          rm -rf storage
          ln -sf ../rahantara/storage/app/public storage

          # Storage symlink in Laravel app
          cd /home/rahe9358/rahantara
          rm -rf public/storage
          ln -sf ../storage/app/public public/storage

          # Fix permissions
          chmod -R 775 storage/ bootstrap/cache/

          # Clear and cache Laravel configs
          /opt/cpanel/ea-php83/root/usr/bin/php artisan config:clear
          /opt/cpanel/ea-php83/root/usr/bin/php artisan cache:clear
          /opt/cpanel/ea-php83/root/usr/bin/php artisan route:clear
          /opt/cpanel/ea-php83/root/usr/bin/php artisan view:clear
          /opt/cpanel/ea-php83/root/usr/bin/php artisan config:cache
          /opt/cpanel/ea-php83/root/usr/bin/php artisan route:cache
          /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache

          # Restart Passenger
          touch /home/rahe9358/rahantara/tmp/restart.txt
          echo "✓ Deployment completed and Passenger restarted"

    - name: Deployment completed
      run: echo "Rahantara auto-deployment finished at $(date)"
