name: Auto-Deploy Laravel Rahantara to cPanel with Symlinks
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
        
    - name: Install Composer dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Create deployment info
      run: |
        echo "Deployment started at: $(date)" > deployment-info.txt
        echo "Commit: ${{ github.sha }}" >> deployment-info.txt
        echo "Branch: ${{ github.ref_name }}" >> deployment-info.txt
        
    - name: Prepare deployment structure
      run: |
        mkdir -p deployment/rahantara
        mkdir -p deployment/public_html/rahantara.id
        
        # Copy Laravel app (excluding public folder)
        rsync -av --progress ./ deployment/rahantara/ \
          --exclude=public \
          --exclude=.git \
          --exclude=node_modules \
          --exclude=tests \
          --exclude=.github \
          --exclude=deployment
          
        # Copy public folder contents INCLUDING build folder
        cp -r public/* deployment/public_html/rahantara.id/
        
        # Ensure build folder is copied (jika ada)
        if [ -d "public/build" ]; then
          cp -r public/build deployment/public_html/rahantara.id/
          echo "Build folder copied successfully"
        else
          echo "Warning: Build folder not found"
        fi
        
        # Create custom index.php
        cat > deployment/public_html/rahantara.id/index.php << 'EOF'
        <?php
        
        use Illuminate\Contracts\Http\Kernel;
        use Illuminate\Http\Request;
        
        define('LARAVEL_START', microtime(true));
        
        require __DIR__.'/../../rahantara/vendor/autoload.php';
        
        $app = require_once __DIR__.'/../../rahantara/bootstrap/app.php';
        
        $kernel = $app->make(Kernel::class);
        
        $response = $kernel->handle(
            $request = Request::capture()
        )->send();
        
        $kernel->terminate($request, $response);
        EOF
        
        # Create .htaccess
        cat > deployment/public_html/rahantara.id/.htaccess << 'EOF'
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews -Indexes
            </IfModule>
        
            RewriteEngine On
        
            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
        
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_URI} (.+)/$
            RewriteRule ^ %1 [L,R=301]
        
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.php [L]
        </IfModule>
        EOF
        
    - name: Deploy Laravel App to /rahantara
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PUBLIC_FTP_SERVER }}
        username: ${{ secrets.PUBLIC_FTP_USERNAME }}
        password: ${{ secrets.PUBLIC_FTP_PASSWORD }}
        port: ${{ secrets.PUBLIC_FTP_PORT }}
        local-dir: ./deployment/rahantara/
        server-dir: /rahantara/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          **/.github/**
          **/deployment/**
          
    - name: Deploy Public Assets (Including Build Folder)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PUBLIC_FTP_SERVER }}
        username: ${{ secrets.PUBLIC_FTP_USERNAME }}
        password: ${{ secrets.PUBLIC_FTP_PASSWORD }}
        port: ${{ secrets.PUBLIC_FTP_PORT }}
        local-dir: ./deployment/public_html/rahantara.id/
        server-dir: /public_html/rahantara.id/
        
    - name: Create symlink script
      run: |
        cat > symlink-setup.sh << 'EOF'
        #!/bin/bash
        
        # Create storage symlink in public_html
        cd /home/rahe9358/public_html/rahantara.id
        if [ -L "storage" ]; then
            rm storage
        fi
        if [ -d "storage" ]; then
            rm -rf storage
        fi
        ln -sf ../../rahantara/storage/app/public storage
        
        # Create storage symlink in Laravel app
        cd /home/rahe9358/rahantara
        if [ ! -L "public/storage" ]; then
            if [ -d "public/storage" ]; then
                rm -rf public/storage
            fi
            ln -sf ../storage/app/public public/storage
        fi
        
        # Set proper permissions
        chmod -R 775 storage/
        chmod -R 775 bootstrap/cache/
        
        # Clear and cache Laravel configurations
        if [ -f ".env" ]; then
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            
            # Only cache in production
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
        fi
        
        echo "Symlinks created successfully"
        echo "Build assets should be in: /home/rahe9358/public_html/rahantara.id/build/"
        
        # Check if build folder exists
        if [ -d "/home/rahe9358/public_html/rahantara.id/build" ]; then
            echo "✓ Build folder found"
            ls -la /home/rahe9358/public_html/rahantara.id/build/
        else
            echo "✗ Build folder NOT found"
        fi
        EOF
        
    - name: Deploy symlink script
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PUBLIC_FTP_SERVER }}
        username: ${{ secrets.PUBLIC_FTP_USERNAME }}
        password: ${{ secrets.PUBLIC_FTP_PASSWORD }}
        port: ${{ secrets.PUBLIC_FTP_PORT }}
        local-dir: ./
        server-dir: /
        include: |
          symlink-setup.sh
          
    - name: Execute symlink setup via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          chmod +x /home/rahe9358/symlink-setup.sh
          bash /home/rahe9358/symlink-setup.sh
          rm /home/rahe9358/symlink-setup.sh
          
    - name: Deployment completed
      run: |
        echo "Rahantara auto-deployment completed!"
        echo "Deployed at: $(date)"
        echo "All symlinks have been created automatically"
