name: Deploy Laravel to cPanel via FTP

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install NPM dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Create deployment info
      run: |
        echo "Deployment started at: $(date)" > deployment-info.txt
        echo "Commit: ${{ github.sha }}" >> deployment-info.txt
        echo "Branch: ${{ github.ref_name }}" >> deployment-info.txt

    - name: Deploy to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PUBLIC_FTP_SERVER }}
        username: ${{ secrets.PUBLIC_FTP_USERNAME }}
        password: ${{ secrets.PUBLIC_FTP_PASSWORD }}
        port: ${{ secrets.PUBLIC_FTP_PORT }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          **/.github/**
          **/.env.example
          **/README.md
          **/package-lock.json
          **/composer.lock
          **/.editorconfig
          **/.gitignore
          **/.styleci.yml
          **/phpunit.xml
          **/vite.config.js
          **/tailwind.config.js

    - name: ✅ Deployment completed
      run: |
        echo "Prosed deploy done!"
        echo "Deployed at: $(date)"
